-- TypeMaster schema for Supabase (Postgres)
-- Idempotent: safe to run multiple times.
-- Run this in Supabase Dashboard -> SQL Editor.
--
-- v0.5.0 anti-cheat hardening:
--   * All writes go through SECURITY DEFINER functions that validate input
--     server-side. Direct INSERT/UPDATE via the public anon key is blocked.
--   * Best-score upsert is atomic (no read-then-write race).
--   * Certificates are unique per (name, tier) and validated against tier rules.

-- ============================================================
-- 1. game_sessions — one row per player (best score only)
-- ============================================================
create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  name text not null,
  duration integer not null default 30,
  wpm integer not null default 0,
  accuracy numeric not null default 100,
  errors integer not null default 0,
  created_at timestamptz default now(),

  constraint valid_wpm check (wpm >= 0 AND wpm <= 400),
  constraint valid_accuracy check (accuracy >= 0 AND accuracy <= 100),
  constraint valid_errors check (errors >= 0),
  constraint valid_duration check (duration > 0 AND duration <= 300)
);

create unique index if not exists game_sessions_name_unique on public.game_sessions (name);

create index if not exists game_sessions_leaderboard_idx
  on public.game_sessions (wpm desc, accuracy desc, errors asc, id desc);

alter table public.game_sessions enable row level security;

drop policy if exists "Allow public select" on public.game_sessions;
create policy "Allow public select" on public.game_sessions
  for select using (true);

drop policy if exists "Allow public insert" on public.game_sessions;
drop policy if exists "Allow public update" on public.game_sessions;
-- No public INSERT/UPDATE policies: all writes go through submit_game_session().

-- ============================================================
-- 2. game_history — append-only log of every game played
-- ============================================================
create table if not exists public.game_history (
  id bigint generated by default as identity primary key,
  name text not null,
  text_mode text not null default 'normal',
  duration integer not null,
  wpm integer not null,
  accuracy numeric not null,
  errors integer not null,
  created_at timestamptz default now(),

  constraint valid_history_wpm check (wpm >= 0 AND wpm <= 400),
  constraint valid_history_accuracy check (accuracy >= 0 AND accuracy <= 100),
  constraint valid_history_errors check (errors >= 0),
  constraint valid_history_duration check (duration > 0 AND duration <= 300)
);

create index if not exists game_history_name_idx
  on public.game_history (name, created_at desc);

alter table public.game_history enable row level security;

drop policy if exists "Allow public select history" on public.game_history;
create policy "Allow public select history" on public.game_history
  for select using (true);

drop policy if exists "Allow public insert history" on public.game_history;
-- No public INSERT policy: history is written by submit_game_session().

-- ============================================================
-- 3. certificates — earned certificates
-- ============================================================
create table if not exists public.certificates (
  id text primary key,
  name text not null,
  tier text not null,
  wpm integer not null,
  accuracy numeric not null,
  created_at timestamptz default now()
);

create index if not exists certificates_name_idx
  on public.certificates (name);

-- One certificate per player per tier.
create unique index if not exists certificates_name_tier_unique
  on public.certificates (name, tier);

alter table public.certificates enable row level security;

drop policy if exists "Allow public select certs" on public.certificates;
create policy "Allow public select certs" on public.certificates
  for select using (true);

drop policy if exists "Allow public insert certs" on public.certificates;
-- No public INSERT policy: certificates are written by award_certificate().

-- ============================================================
-- 4. submit_game_session — validated, atomic score submission
--
-- Replaces client-side validation + read-compare-update logic.
-- Returns jsonb: { saved: boolean } where saved=true means a new best.
-- Raises an exception on invalid input (supabase-js surfaces it as an error).
-- ============================================================
create or replace function public.submit_game_session(
  p_name text,
  p_duration integer,
  p_wpm integer,
  p_accuracy numeric,
  p_errors integer,
  p_text_mode text default 'normal'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_mode text;
  v_saved boolean := false;
begin
  -- Sanitize + validate name (mirrors app logic)
  v_name := btrim(regexp_replace(coalesce(p_name, ''), '[\x00-\x1f\x7f]', '', 'g'));
  v_name := substring(v_name from 1 for 20);
  if v_name is null or length(v_name) = 0 then
    raise exception 'Name is required';
  end if;

  v_mode := coalesce(p_text_mode, 'normal');
  if v_mode not in ('normal', 'numbers', 'punctuation', 'quotes') then
    v_mode := 'normal';
  end if;

  -- Validate numbers
  if p_duration is null or p_duration <= 0 or p_duration > 300
     or p_wpm is null or p_wpm < 0 or p_wpm > 400
     or p_accuracy is null or p_accuracy < 0 or p_accuracy > 100
     or p_errors is null or p_errors < 0 or p_errors > 999999 then
    raise exception 'Invalid score data';
  end if;

  -- Every game goes to history
  insert into public.game_history (name, text_mode, duration, wpm, accuracy, errors)
  values (v_name, v_mode, p_duration, p_wpm, p_accuracy, p_errors);

  -- Atomic upsert of the best score: the DO UPDATE ... WHERE clause means the
  -- row is only replaced when the new score is strictly better
  -- (wpm desc, accuracy desc, errors asc). No race conditions possible.
  insert into public.game_sessions as gs (name, duration, wpm, accuracy, errors)
  values (v_name, p_duration, p_wpm, p_accuracy, p_errors)
  on conflict (name) do update
    set duration   = excluded.duration,
        wpm        = excluded.wpm,
        accuracy   = excluded.accuracy,
        errors     = excluded.errors,
        created_at = now()
    where (excluded.wpm, excluded.accuracy, -excluded.errors)
        > (gs.wpm, gs.accuracy, -gs.errors);

  v_saved := found;

  return jsonb_build_object('saved', v_saved);
end;
$$;

revoke all on function public.submit_game_session(text, integer, integer, numeric, integer, text) from public;
grant execute on function public.submit_game_session(text, integer, integer, numeric, integer, text) to anon, authenticated;

-- ============================================================
-- 5. award_certificate — validated certificate issuance
--
-- Validates the tier thresholds and the ID format/prefix before inserting.
-- Returns true if a new row was inserted, false if it already existed
-- (duplicate id or duplicate (name, tier)) so callers can retry collisions.
-- ============================================================
create or replace function public.award_certificate(
  p_id text,
  p_name text,
  p_tier text,
  p_wpm integer,
  p_accuracy numeric
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prefix text;
begin
  -- Look up tier rules (single source of truth lives here, server-side)
  case p_tier
    when 'bronze'  then v_prefix := 'B';
    when 'silver'  then v_prefix := 'S';
    when 'gold'    then v_prefix := 'G';
    when 'diamond' then v_prefix := 'D';
    else raise exception 'Unknown tier';
  end case;

  if p_wpm < (case p_tier
                when 'bronze' then 40 when 'silver' then 60
                when 'gold' then 80 else 100 end)
     or p_accuracy < (case p_tier
                when 'bronze' then 80 when 'silver' then 85
                when 'gold' then 90 else 95 end) then
    raise exception 'Tier requirements not met';
  end if;

  -- ID must match TYM<prefix>.XXX.XXXX with the correct tier prefix
  if coalesce(p_id, '') !~ ('^TYM' || v_prefix || '\.[A-Z0-9]{3}\.[A-Z0-9]{4}$') then
    raise exception 'Invalid certificate id';
  end if;

  insert into public.certificates (id, name, tier, wpm, accuracy)
  values (p_id, left(btrim(coalesce(p_name, '')), 20), p_tier, p_wpm, p_accuracy)
  on conflict do nothing;

  return found;
end;
$$;

revoke all on function public.award_certificate(text, text, text, integer, numeric) from public;
grant execute on function public.award_certificate(text, text, text, integer, numeric) to anon, authenticated;

-- ============================================================
-- 6. Cleanup note for legacy duplicate certificates (run once if needed):
--
-- delete from public.certificates a using public.certificates b
-- where a.name = b.name and a.tier = b.tier and a.created_at > b.created_at;
-- ============================================================
