-- TypeMaster schema for Supabase (Postgres)
-- Idempotent: safe to run multiple times.
-- Run this in Supabase Dashboard -> SQL Editor.

-- 1. Table
create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  name text not null,
  duration integer not null default 30,
  wpm integer not null default 0,
  accuracy numeric not null default 100,
  errors integer not null default 0,
  created_at timestamptz default now(),

  -- CHECK constraints for data integrity
  constraint valid_wpm check (wpm >= 0 AND wpm <= 400),
  constraint valid_accuracy check (accuracy >= 0 AND accuracy <= 100),
  constraint valid_errors check (errors >= 0),
  constraint valid_duration check (duration > 0 AND duration <= 300)
);

-- 2. One row per player name (prevents duplicate leaderboard entries under concurrency).
-- NOTE: if you already have duplicate names, run a cleanup first:
--   delete from public.game_sessions a using public.game_sessions b
--   where a.name = b.name and a.id < b.id;
create unique index if not exists game_sessions_name_unique on public.game_sessions (name);

-- 3. Composite index for leaderboard query performance
create index if not exists game_sessions_leaderboard_idx
  on public.game_sessions (wpm desc, accuracy desc, errors asc, id desc);

-- 4. Row Level Security: only the policies below can touch this table.
alter table public.game_sessions enable row level security;

drop policy if exists "Allow public select" on public.game_sessions;
create policy "Allow public select" on public.game_sessions
  for select using (true);

drop policy if exists "Allow public insert" on public.game_sessions;
create policy "Allow public insert" on public.game_sessions
  for insert with check (true);

-- NOTE: No public UPDATE policy. All score updates go through server actions
-- which handle the read-compare-update logic securely.
